const API_URL=window.GH_CONFIG?.API_URL||"";
const $=id=>document.getElementById(id);
const state={token:sessionStorage.getItem("ghAdminToken")||"",tab:"submissions",submissions:{offset:0,hasMore:false},feedback:{offset:0,hasMore:false},content:{offset:0,hasMore:false},edit:null};
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);}
function fmtDate(v){if(!v)return"";const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString("ja-JP");}
async function api(action,payload={}){if(!API_URL)throw Error("API URLが設定されていません。");const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,adminToken:state.token,...payload})});if(!r.ok)throw Error(`通信に失敗しました（${r.status}）`);const data=await r.json();if(!data.ok)throw Error(data.message||"処理できませんでした。");return data;}
function setLoggedIn(on){$("adminLogin").hidden=on;$("adminShell").hidden=!on;if(on)loadActiveTab();}
function logout(){state.token="";sessionStorage.removeItem("ghAdminToken");setLoggedIn(false);$("adminPassword").value="";}
$("adminLoginForm").addEventListener("submit",async e=>{e.preventDefault();const msg=$("adminLoginMessage"),button=e.currentTarget.querySelector("button");msg.textContent="";button.disabled=true;try{const data=await api("adminLogin",{password:$("adminPassword").value});state.token=data.adminToken;sessionStorage.setItem("ghAdminToken",state.token);setLoggedIn(true);}catch(err){msg.textContent=err.message;}finally{button.disabled=false;}});
$("adminLogout").addEventListener("click",logout);
document.querySelectorAll(".admin-tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.toggle("active",x===btn));state.tab=btn.dataset.adminTab;["Submissions","Feedback","Content"].forEach(n=>$("adminPanel"+n).hidden=n.toLowerCase()!==state.tab);loadActiveTab();}));
function loadActiveTab(){if(state.tab==="submissions")loadSubmissions(true);else if(state.tab==="feedback")loadFeedback(true);else loadContent(true);}
function typeLabel(t){return({new:"新規登録",add:"追記",fix:"修正",video:"動画",letter:"思い出投稿",fanartGeneral:"通常FA",fanartAdult:"成人向けFA"})[t]||t;}
async function loadSubmissions(reset){const box=$("submissionList");if(reset){state.submissions.offset=0;box.innerHTML='<div class="admin-empty">読み込んでいます。</div>';}try{const data=await api("adminListSubmissions",{q:$("submissionQuery").value,status:$("submissionStatus").value,type:$("submissionType").value,offset:state.submissions.offset,limit:30});if(reset)box.innerHTML="";renderSubmissions(data.items||[],box);state.submissions.offset=data.nextOffset||0;state.submissions.hasMore=!!data.hasMore;$("submissionMore").hidden=!data.hasMore;if(!box.children.length)box.innerHTML='<div class="admin-empty">該当する申請はありません。</div>';}catch(err){if(/ログイン|セッション/.test(err.message)){logout();return;}box.innerHTML=`<div class="admin-empty">${esc(err.message)}</div>`;}}
function submissionPreview(item){
  const p=item.payload||{};
  if(item.submissionType==="fanartGeneral"||item.submissionType==="fanartAdult"){
    const image=String(p.imageUrl||"");
    return `<div class="admin-media-preview">${image?`<img src="${esc(image)}" alt="申請ファンアート" loading="lazy">`:""}<dl><div><dt>作品名</dt><dd>${esc(p.title||"無題")}</dd></div><div><dt>作者</dt><dd>${esc(p.authorName||"匿名")}</dd></div><div><dt>区分</dt><dd>${item.submissionType==="fanartAdult"?"成人向け":"通常"}</dd></div><div><dt>補足</dt><dd>${esc(p.note||"")}</dd></div></dl></div>`;
  }
  if(item.submissionType==="video"){
    const url=String(p.videoUrl||"");
    return `<div class="admin-media-preview"><dl><div><dt>動画タイトル</dt><dd>${esc(p.videoTitle||"")}</dd></div><div><dt>種類</dt><dd>${esc(p.videoCategory||"")}</dd></div><div><dt>URL</dt><dd>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">動画を開く</a>`:""}</dd></div><div><dt>補足</dt><dd>${esc(p.note||"")}</dd></div></dl></div>`;
  }
  return `<details open><summary>申請内容</summary><pre>${esc(JSON.stringify(p,null,2))}</pre></details>`;
}
function renderSubmissions(items,box){items.forEach(item=>{const card=document.createElement("article");card.className="admin-card "+(item.status==="確認待ち"?"is-pending":item.status.includes("非許可")?"is-rejected":"is-approved");const current=item.current?`<details><summary>現在の登録内容</summary><pre>${esc(JSON.stringify(item.current,null,2))}</pre></details>`:"";card.innerHTML=`<div class="admin-card-head"><div><h3>${esc(item.activityName||"名称未設定")}</h3><p class="admin-card-meta">${esc(typeLabel(item.submissionType))} / ${esc(item.submissionId)} / ${esc(fmtDate(item.receivedAt))}</p></div><span class="admin-badge">${esc(item.status)}</span></div><div class="admin-card-body">${current}${submissionPreview(item)}</div><div class="admin-card-actions"><div class="admin-note"><textarea placeholder="審査メモ（任意）">${esc(item.reviewNote||"")}</textarea></div>${item.status==="確認待ち"?'<button class="admin-button gold" data-decision="approve" type="button">許可（掲載）</button><button class="admin-button danger" data-decision="reject" type="button">非許可（掲載不可）</button>':""}</div>`;card.querySelectorAll("[data-decision]").forEach(btn=>btn.addEventListener("click",async()=>{const approve=btn.dataset.decision==="approve";if(!confirm(`${approve?"許可して掲載":"非許可"}にしますか？`))return;btn.disabled=true;try{await api("adminDecideSubmission",{submissionId:item.submissionId,decision:btn.dataset.decision,reviewNote:card.querySelector("textarea").value});await loadSubmissions(true);}catch(err){alert(err.message);btn.disabled=false;}}));box.appendChild(card);});}
$("submissionSearch").addEventListener("click",()=>loadSubmissions(true));$("submissionMore").addEventListener("click",()=>loadSubmissions(false));$("submissionQuery").addEventListener("keydown",e=>{if(e.key==="Enter")loadSubmissions(true);});
$("repairPublished")?.addEventListener("click",async e=>{if(!confirm("許可済みのプロフィール・動画・FAを公開シートへ再反映しますか？"))return;const button=e.currentTarget;button.disabled=true;try{const d=await api("adminRepairPublishedData");alert(`再反映しました。成功 ${d.success||0}件 / エラー ${d.errors||0}件`);await loadSubmissions(true);}catch(err){alert(err.message);}finally{button.disabled=false;}});
async function loadFeedback(reset){const box=$("feedbackAdminList");if(reset){state.feedback.offset=0;box.innerHTML='<div class="admin-empty">読み込んでいます。</div>';}try{const data=await api("adminListFeedback",{q:$("feedbackAdminQuery").value,status:$("feedbackAdminStatus").value,offset:state.feedback.offset,limit:30});if(reset)box.innerHTML="";renderFeedback(data.items||[],box);state.feedback.offset=data.nextOffset||0;$("feedbackAdminMore").hidden=!data.hasMore;if(!box.children.length)box.innerHTML='<div class="admin-empty">該当するお問い合わせはありません。</div>';}catch(err){if(/ログイン|セッション/.test(err.message)){logout();return;}box.innerHTML=`<div class="admin-empty">${esc(err.message)}</div>`;}}
function renderFeedback(items,box){items.forEach(item=>{const card=document.createElement("article");card.className="admin-card";card.innerHTML=`<div class="admin-card-head"><div><h3>${esc(item.relatedActivityName||"サイト全般")}</h3><p class="admin-card-meta">${esc(item.feedbackId)} / ${esc(fmtDate(item.receivedAt))}</p></div><span class="admin-badge">${esc(item.status)}</span></div><div class="admin-card-body"><div class="admin-feedback-message">${esc(item.message)}</div>${item.pageUrl?`<p><small>送信ページ：${esc(item.pageUrl)}</small></p>`:""}</div><div class="admin-feedback-controls"><div class="admin-field"><label>対応状況</label><select><option>未確認</option><option>対応中</option><option>対応済み</option><option>対応不要</option></select></div><div class="admin-field"><label>対応メモ</label><textarea>${esc(item.reviewNote||"")}</textarea></div><button class="admin-button" type="button">保存</button></div>`;const select=card.querySelector("select");select.value=item.status||"未確認";card.querySelector("button.admin-button").addEventListener("click",async e=>{const button=e.currentTarget;button.disabled=true;try{await api("adminUpdateFeedback",{feedbackId:item.feedbackId,status:select.value,reviewNote:card.querySelector("textarea").value});await loadFeedback(true);}catch(err){alert(err.message);button.disabled=false;}});box.appendChild(card);});}
$("feedbackAdminSearch").addEventListener("click",()=>loadFeedback(true));$("feedbackAdminMore").addEventListener("click",()=>loadFeedback(false));$("feedbackAdminQuery").addEventListener("keydown",e=>{if(e.key==="Enter")loadFeedback(true);});
async function loadContent(reset){const box=$("contentList");if(reset){state.content.offset=0;box.innerHTML='<div class="admin-empty">読み込んでいます。</div>';}try{const data=await api("adminSearchContent",{contentType:$("contentType").value,q:$("contentQuery").value,offset:state.content.offset,limit:30});if(reset)box.innerHTML="";renderContent(data.items||[],box);state.content.offset=data.nextOffset||0;$("contentMore").hidden=!data.hasMore;if(!box.children.length)box.innerHTML='<div class="admin-empty">該当する登録内容はありません。</div>';}catch(err){if(/ログイン|セッション/.test(err.message)){logout();return;}box.innerHTML=`<div class="admin-empty">${esc(err.message)}</div>`;}}
function renderContent(items,box){items.forEach(item=>{const card=document.createElement("article");card.className="admin-card";card.innerHTML=`<div class="admin-card-head"><div><h3>${esc(item.title||"名称未設定")}</h3><p class="admin-card-meta">${esc(item.subtitle||"")} / ${esc(item.id)}</p></div><span class="admin-badge">${esc(item.status||"")}</span></div><div class="admin-card-actions"><button class="admin-button" data-edit type="button">修正する</button><button class="admin-button danger" data-delete type="button">削除する</button></div>`;card.querySelector("[data-edit]").addEventListener("click",()=>openEditor(item));card.querySelector("[data-delete]").addEventListener("click",async()=>{const extra=item.contentType==="profiles"?"\nこのVTuberに紐づく動画と思い出メッセージも削除されます。":"";if(!confirm(`「${item.title}」を削除しますか？${extra}\nこの操作は元に戻せません。`))return;try{const data=await api("adminDeleteContent",{contentType:item.contentType,id:item.id});alert(data.message||"削除しました。");loadContent(true);}catch(err){alert(err.message);}});box.appendChild(card);});}
$("contentSearch").addEventListener("click",()=>loadContent(true));$("contentMore").addEventListener("click",()=>loadContent(false));$("contentType").addEventListener("change",()=>loadContent(true));$("contentQuery").addEventListener("keydown",e=>{if(e.key==="Enter")loadContent(true);});
const fieldDefs={profiles:[["activityName","活動名"],["reading","読み方"],["nickname","愛称"],["fanName","ファンネーム"],["fanMark","ファンマーク"],["affiliation","所属"],["activityStartDate","活動開始日"],["graduationDate","卒業日"],["youtubeUrl","YouTubeリンク"],["xUrl","Xリンク"],["status","公開状態"],["dataJson","詳細情報（JSON）","json"]],videos:[["activityName","VTuber名"],["profileId","プロフィールID"],["title","動画タイトル"],["url","動画リンク"],["videoType","動画種類"],["publicStatus","公開状態"],["note","補足","textarea"]],fanartGeneral:[["activityName","VTuber名"],["title","作品名"],["authorName","作者名"],["publicStatus","公開状態"],["note","補足","textarea"]],fanartAdult:[["activityName","VTuber名"],["title","作品名"],["authorName","作者名"],["publicStatus","公開状態"],["note","補足","textarea"]],letters:[["activityName","VTuber名"],["authorName","投稿者名"],["message","メッセージ","textarea"]]};
function openEditor(item){state.edit=item;const fields=$("adminEditFields");$("adminEditTitle").textContent=`${item.title}を修正`;fields.innerHTML="";(fieldDefs[item.contentType]||[]).forEach(([key,label,type])=>{const wrap=document.createElement("div");wrap.className="admin-field "+((type==="textarea"||type==="json")?"full":"");const value=key==="dataJson"?JSON.stringify(item.data.dataJson||{},null,2):item.data[key]??"";wrap.innerHTML=`<label for="adminEdit_${key}">${esc(label)}</label>${type==="textarea"||type==="json"?`<textarea id="adminEdit_${key}" name="${key}" class="${type==="json"?"json-editor":""}">${esc(value)}</textarea>`:`<input id="adminEdit_${key}" name="${key}" value="${esc(value)}">`}`;fields.appendChild(wrap);});$("adminEditMessage").textContent="";$("adminEditDialog").hidden=false;document.body.style.overflow="hidden";}
function closeEditor(){$("adminEditDialog").hidden=true;document.body.style.overflow="";state.edit=null;}
document.querySelectorAll("[data-admin-edit-close]").forEach(b=>b.addEventListener("click",closeEditor));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("adminEditDialog").hidden)closeEditor();});
$("adminEditForm").addEventListener("submit",async e=>{e.preventDefault();if(!state.edit)return;const data=Object.fromEntries(new FormData(e.currentTarget).entries());if("dataJson" in data){try{data.dataJson=JSON.parse(data.dataJson||"{}");}catch(_){$("adminEditMessage").textContent="詳細情報（JSON）の形式が正しくありません。";return;}}const btn=$("adminEditSave");btn.disabled=true;try{await api("adminUpdateContent",{contentType:state.edit.contentType,id:state.edit.id,data});closeEditor();loadContent(true);}catch(err){$("adminEditMessage").textContent=err.message;}finally{btn.disabled=false;}});
if(state.token)setLoggedIn(true);else setLoggedIn(false);
